import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from "@/biz/providers/react-query-provider";
import { NextAuthProvider } from "@/biz/providers/next-auth-provider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getServerSession(authOptions);

    return (
        <html lang="ko">
            <body className={inter.className}>
                <NextAuthProvider session={session}>
                    <ReactQueryProvider>{children}</ReactQueryProvider>
                </NextAuthProvider>
            </body>
        </html>
    );
}
